language: python
python:
  - "3.6"
install:
  - "pip install -r requirements.txt"
  - "pip install -r tests/test-requirements.txt"
script:
    - pytest --cov-report= --cov=asm68 tests/
after_success:
    - coveralls
