class Mnemonic:

    _instances = {}

    def __new__(cls, mnemonic):
        if len(mnemonic) < 1:
            raise ValueError("Mnemonic cannot be empty")
        if not (mnemonic[0].isalpha() and mnemonic[0].isupper()):
            raise ValueError("Mnemonic {} does not begin with an uppercase alphabetic character".format(mnemonic))
        if (len(mnemonic) > 1) and not (mnemonic[1:].isalnum() and all(c.isupper() for c in mnemonic[1:] if c.isalpha())):
            raise ValueError("Mnemonic {} is not uppercase alphanumeric".format(mnemonic))
        if mnemonic in cls._instances:
            return cls._instances[mnemonic]
        obj = object.__new__(cls)
        obj._mnemonic = mnemonic
        cls._instances[mnemonic] = obj
        return obj

    def __str__(self):
        return self._mnemonic

    def __repr__(self):
        return "{}({})".format(self.__class__.__name__, self._mnemonic)



ABX = Mnemonic('ABX')
ADCA = Mnemonic('ADCA')
ADCB = Mnemonic('ADCB')
ADDA = Mnemonic('ADDA')
ADDB = Mnemonic('ADDB')
ADDD = Mnemonic('ADDD')
ANDA = Mnemonic('ANDA')
ANDB = Mnemonic('ANDB')
ANDCC = Mnemonic('ANDCC')
ASLA = Mnemonic('ASLA')
ASLB = Mnemonic('ASLB')
ASL = Mnemonic('ASL')
ASRA = Mnemonic('ASRA')
ASRB = Mnemonic('ASRB')
ASR = Mnemonic('ASR')
BEQ = Mnemonic('BEQ')
BITA = Mnemonic('BITA')
BITB = Mnemonic('BITB')
BHS = Mnemonic('BHS')
BLO = Mnemonic('BLO')
BNE = Mnemonic('BNE')
BPL = Mnemonic('BPL')
BRA = Mnemonic('BRA')
CLRA = Mnemonic('CLRA')
CLRB = Mnemonic('CLRB')
CLR = Mnemonic('CLR')
CMPA = Mnemonic('CMPA')
CMPB = Mnemonic('CMPB')
CMPD = Mnemonic('CMPD')
CMPS = Mnemonic('CMPS')
CMPU = Mnemonic('CMPU')
CMPX = Mnemonic('CMPX')
CMPY = Mnemonic('CMPY')
COMA = Mnemonic('COMA')
COMB = Mnemonic('COMB')
COM = Mnemonic('COM')
CWAI = Mnemonic('CWAI')
DAA = Mnemonic('DAA')
DECA = Mnemonic('DECA')
DECB = Mnemonic('DECB')
DEC = Mnemonic('DEC')
EORA = Mnemonic('EORA')
EORB = Mnemonic('EORB')
EXG = Mnemonic('EXG')
INCA = Mnemonic('INCA')
INCB = Mnemonic('INCB')
INC = Mnemonic('INC')
JMP = Mnemonic('JMP')
JSR = Mnemonic('JSR')
LBRA = Mnemonic('LBRA')
LBNE = Mnemonic('LBNE')
LDA = Mnemonic('LDA')
LDB = Mnemonic('LDB')
LDD = Mnemonic('LDD')
LDS = Mnemonic('LDS')
LDU = Mnemonic('LDU')
LDX = Mnemonic('LDX')
LDY = Mnemonic('LDY')
LEAS = Mnemonic('LEAS')
LEAU = Mnemonic('LEAU')
LEAX = Mnemonic('LEAX')
LEAY = Mnemonic('LEAY')
LSLA = Mnemonic('LSLA')
LSLB = Mnemonic('LSLB')
LSL = Mnemonic('LSL')
LSRA = Mnemonic('LSRA')
LSRB = Mnemonic('LSRB')
LSR = Mnemonic('LSR')
MUL = Mnemonic('MUL')
NEGA = Mnemonic('NEGA')
NEGB = Mnemonic('NEGB')
NEG = Mnemonic('NEG')
NOP = Mnemonic('NOP')
ORA = Mnemonic('ORA')
ORB = Mnemonic('ORB')
ORCC = Mnemonic('ORCC')
PSHS = Mnemonic('PSHS')
PSHU = Mnemonic('PSHU')
PULS = Mnemonic('PULS')
PULU = Mnemonic('PULU')
ROLA = Mnemonic('ROLA')
ROLB = Mnemonic('ROLB')
ROL = Mnemonic('ROL')
RORA = Mnemonic('RORA')
RORB = Mnemonic('RORB')
ROR = Mnemonic('ROR')
RTI = Mnemonic('RTI')
RTS = Mnemonic('RTS')
SBCA = Mnemonic('SBCA')
SBCB = Mnemonic('SBCB')
SEX = Mnemonic('SEX')
STA = Mnemonic('STA')
STB = Mnemonic('STB')
STD = Mnemonic('STD')
STS = Mnemonic('STS')
STU = Mnemonic('STU')
STX = Mnemonic('STX')
STY = Mnemonic('STY')
SUBA = Mnemonic('SUBA')
SUBB = Mnemonic('SUBB')
SUBD = Mnemonic('SUBD')
SWI = Mnemonic('SWI')
SWI2 = Mnemonic('SWI2')
SWI3 = Mnemonic('SWI3')
SYNC = Mnemonic('SYNC')
TFR = Mnemonic('TFR')
TSTA = Mnemonic('TSTA')
TSTB = Mnemonic('TSTB')
TST = Mnemonic('TST')

ORG = Mnemonic('ORG')
FCB = Mnemonic('FCB')
FDB = Mnemonic('FDB')
# TODO: Setdp

