from util import typename


class Mnemonic:

    def __init__(self, mnemonic):
        self._mnemonic = mnemonic

    def __str__(self):
        return self._mnemonic

    def __repr__(self):
        return "{}({})".format(typename(self), self._mnemonic)

    def __hash__(self):
        return hash(self._mnemonic)

    def __eq__(self, other):
        if not isinstance(other, type(self)):
            return NotImplemented
        return self._mnemonic == other._mnemonic



ABX = Mnemonic('ABX')
ADCA = Mnemonic('ADCA')
ADCB = Mnemonic('ADCB')
ADCD = Mnemonic('ADCD')
ADCR = Mnemonic('ADCR')
ADDA = Mnemonic('ADDA')
ADDB = Mnemonic('ADDB')
ADDD = Mnemonic('ADDD')
ADDE = Mnemonic('ADDE')
ADDF = Mnemonic('ADDF')
ADDR = Mnemonic('ADDR')
ADDW = Mnemonic('ADDW')
ANDA = Mnemonic('ANDA')
ANDB = Mnemonic('ANDB')
ANDCC = Mnemonic('ANDCC')
ASLA = Mnemonic('ASLA')
ASLB = Mnemonic('ASLB')
ASL = Mnemonic('ASL')
ASRA = Mnemonic('ASRA')
ASRB = Mnemonic('ASRB')
ASR = Mnemonic('ASR')
BEQ = Mnemonic('BEQ')
BITA = Mnemonic('BITA')
BITB = Mnemonic('BITB')
BITMD = Mnemonic('BITMD')
BHS = Mnemonic('BHS')
BLO = Mnemonic('BLO')
BNE = Mnemonic('BNE')
BPL = Mnemonic('BPL')
BRA = Mnemonic('BRA')
CLRA = Mnemonic('CLRA')
CLRB = Mnemonic('CLRB')
CLR = Mnemonic('CLR')
CMPA = Mnemonic('CMPA')
CMPB = Mnemonic('CMPB')
CMPD = Mnemonic('CMPD')
CMPR = Mnemonic('CMPR')
CMPS = Mnemonic('CMPS')
CMPU = Mnemonic('CMPU')
CMPX = Mnemonic('CMPX')
CMPY = Mnemonic('CMPY')
COMA = Mnemonic('COMA')
COMB = Mnemonic('COMB')
COM = Mnemonic('COM')
CWAI = Mnemonic('CWAI')
DAA = Mnemonic('DAA')
DECA = Mnemonic('DECA')
DECB = Mnemonic('DECB')
DECD = Mnemonic('DECD')
DECE = Mnemonic('DECE')
DECF = Mnemonic('DECF')
DECW = Mnemonic('DECW')
DEC = Mnemonic('DEC')
EORA = Mnemonic('EORA')
EORB = Mnemonic('EORB')
EXG = Mnemonic('EXG')
INCA = Mnemonic('INCA')
INCB = Mnemonic('INCB')
INCD = Mnemonic('INCD')
INCE = Mnemonic('INCE')
INCF = Mnemonic('INCF')
INCW = Mnemonic('INCW')
INC = Mnemonic('INC')
JMP = Mnemonic('JMP')
JSR = Mnemonic('JSR')
LBRA = Mnemonic('LBRA')
LBNE = Mnemonic('LBNE')
LDA = Mnemonic('LDA')
LDB = Mnemonic('LDB')
LDD = Mnemonic('LDD')
LDE = Mnemonic('LDE')
LDF = Mnemonic('LDF')
LDMD = Mnemonic('LDMD')
LDQ = Mnemonic('LDQ')
LDW = Mnemonic('LDW')
LDS = Mnemonic('LDS')
LDU = Mnemonic('LDU')
LDX = Mnemonic('LDX')
LDY = Mnemonic('LDY')
LEAS = Mnemonic('LEAS')
LEAU = Mnemonic('LEAU')
LEAX = Mnemonic('LEAX')
LEAY = Mnemonic('LEAY')
LSLA = Mnemonic('LSLA')
LSLB = Mnemonic('LSLB')
LSL = Mnemonic('LSL')
LSRA = Mnemonic('LSRA')
LSRB = Mnemonic('LSRB')
LSR = Mnemonic('LSR')
MUL = Mnemonic('MUL')
NEGA = Mnemonic('NEGA')
NEGB = Mnemonic('NEGB')
NEG = Mnemonic('NEG')
NOP = Mnemonic('NOP')
ORA = Mnemonic('ORA')
ORB = Mnemonic('ORB')
ORCC = Mnemonic('ORCC')
PSHS = Mnemonic('PSHS')
PSHU = Mnemonic('PSHU')
PULS = Mnemonic('PULS')
PULU = Mnemonic('PULU')
ROLA = Mnemonic('ROLA')
ROLB = Mnemonic('ROLB')
ROL = Mnemonic('ROL')
RORA = Mnemonic('RORA')
RORB = Mnemonic('RORB')
ROR = Mnemonic('ROR')
RTI = Mnemonic('RTI')
RTS = Mnemonic('RTS')
SBCA = Mnemonic('SBCA')
SBCB = Mnemonic('SBCB')
SEX = Mnemonic('SEX')
STA = Mnemonic('STA')
STB = Mnemonic('STB')
STD = Mnemonic('STD')
STE = Mnemonic('STE')
STF = Mnemonic('STF')
STQ = Mnemonic('STQ')
STS = Mnemonic('STS')
STU = Mnemonic('STU')
STW = Mnemonic('STW')
STX = Mnemonic('STX')
STY = Mnemonic('STY')
SUBA = Mnemonic('SUBA')
SUBB = Mnemonic('SUBB')
SUBD = Mnemonic('SUBD')
SWI = Mnemonic('SWI')
SWI2 = Mnemonic('SWI2')
SWI3 = Mnemonic('SWI3')
SYNC = Mnemonic('SYNC')
TFR = Mnemonic('TFR')
TSTA = Mnemonic('TSTA')
TSTB = Mnemonic('TSTB')
TST = Mnemonic('TST')

ORG = Mnemonic('ORG')
FCB = Mnemonic('FCB')
FDB = Mnemonic('FDB')
CALL = Mnemonic('CALL')
# TODO: Setdp

