from frozendict import frozendict

from asm68.addrmodes import *
from asm68.mnemonics import *

OPCODES_6809 = frozendict({
    ABX:   { INH: '3A',                                                                     },
    ADCA:  {              IMM: '89',   DIR: '99',   IDX: 'A9',   EXT: 'B9',                 },
    ADCB:  {              IMM: 'C9',   DIR: 'D9',   IDX: 'E9',   EXT: 'F9',                 },
    ADDA:  {              IMM: '8B',   DIR: '9B',   IDX: 'AB',   EXT: 'BB',                 },
    ADDB:  {              IMM: 'CB',   DIR: 'DB',   IDX: 'EB',   EXT: 'FB',                 },
    ADDD:  {              IMM: 'C3',   DIR: 'D3',   IDX: 'E3',   EXT: 'F3',                 },
    ANDA:  {              IMM: '84',   DIR: '94',   IDX: 'A4',   EXT: 'B4',                 },
    ANDB:  {              IMM: 'C4',   DIR: 'D4',   IDX: 'E4',   EXT: 'F4',                 },
    ANDCC: {              IMM: '1C',                                                        },
    ASLA:  { INH: '48',                                                                     },
    ASLB:  { INH: '58',                                                                     },
    ASL:   {                           DIR: '08',   IDX: '68',   EXT: '78',                 },
    ASRA:  { INH: '47',                                                                     },
    ASRB:  { INH: '57',                                                                     },
    ASR:   {                           DIR: '07',   IDX: '67',   EXT: '77',                 },
    BEQ:   {                                                                   REL8: '27'   },
    BITA:  {              IMM: '85',   DIR: '95',   IDX: 'A5',   EXT: 'B5',                 },
    BITB:  {              IMM: 'C5',   DIR: 'D5',   IDX: 'E5',   EXT: 'F5',                 },
    BHS:   {                                                                   REL8: '24'   },
    BLO:   {                                                                   REL8: '25'   },
    BNE:   {                                                                   REL8: '26'   },
    BPL:   {                                                                   REL8: '2A'   },
    BRA:   {                                                                   REL8: '20'   },
    CLRA:  { INH: '4F',                                                                     },
    CLRB:  { INH: '5F',                                                                     },
    CLR:   {                           DIR: '0F',   IDX: '6F',   EXT: '7F',                 },
    CMPA:  {              IMM: '81',   DIR: '91',   IDX: 'A1',   EXT: 'B1',                 },
    CMPB:  {              IMM: 'C1',   DIR: 'D1',   IDX: 'E1',   EXT: 'F1',                 },
    CMPD:  {              IMM: '1083', DIR: '1093', IDX: '10A3', EXT: '10B3',               },
    CMPS:  {              IMM: '118C', DIR: '119C', IDX: '11AC', EXT: '11BC',               },
    CMPU:  {              IMM: '1183', DIR: '1193', IDX: '11A3', EXT: '11B3',               },
    CMPX:  {              IMM: '8C',   DIR: '9C',   IDX: 'AC',   EXT: 'BC',                 },
    CMPY:  {              IMM: '108C', DIR: '109C', IDX: '10AC', EXT: '10BC',               },
    COMA:  { INH: '43',                                                                     },
    COMB:  { INH: '53',                                                                     },
    COM:   {                           DIR: '03',   IDX: '63',   EXT: '73',                 },
    CWAI:  {              IMM: '3C',                                                        },
    DAA:   { INH: '19',                                                                     },
    DECA:  { INH: '4A',                                                                     },
    DECB:  { INH: '5A',                                                                     },
    DEC:   {                           DIR: '0A',   IDX: '6A',   EXT: '7A',                 },
    EORA:  {              IMM: '88',   DIR: '98',   IDX: 'A8',   EXT: 'B8',                 },
    EORB:  {              IMM: 'C8',   DIR: 'D8',   IDX: 'E8',   EXT: 'F8',                 },
    EXG:   {              IMM: '1E',                                                        },
    INCA:  { INH: '4C',                                                                     },
    INCB:  { INH: '5C',                                                                     },
    INC:   {                           DIR: '0C',   IDX: '6C',   EXT: '7C',                 },
    JMP:   {                           DIR: '0E',   IDX: '6E',   EXT: '7E',                 },
    JSR:   {                           DIR: '9D',   IDX: 'AD',   EXT: 'BD',                 },
    LBRA:  {                                                                  REL16: '16'   },
    LBNE:  {                                                                  REL16: '1026' },
    LDA:   {              IMM: '86',   DIR: '96',   IDX: 'A6',   EXT: 'B6',                 },
    LDB:   {              IMM: 'C6',   DIR: 'D6',   IDX: 'E6',   EXT: 'F6',                 },
    LDD:   {              IMM: 'CC',   DIR: 'DC',   IDX: 'EC',   EXT: 'FC',                 },
    LDS:   {              IMM: '10CE', DIR: '10DE', IDX: '10EE', EXT: '10FE',               },
    LDU:   {              IMM: 'CE',   DIR: 'DE',   IDX: 'EE',   EXT: 'FE',                 },
    LDX:   {              IMM: '8E',   DIR: '9E',   IDX: 'AE',   EXT: 'BE',                 },
    LDY:   {              IMM: '108E', DIR: '109E', IDX: '10AE', EXT: '10BE',               },
    LEAS:  {                                        IDX: '32',                              },
    LEAU:  {                                        IDX: '33',                              },
    LEAX:  {                                        IDX: '30',                              },
    LEAY:  {                                        IDX: '31',                              },
    LSLA:  { INH: '48',                                                                     },
    LSLB:  { INH: '58',                                                                     },
    LSL:   {                           DIR: '08',   IDX: '68',   EXT: '78',                 },
    LSRA:  { INH: '44',                                                                     },
    LSRB:  { INH: '54',                                                                     },
    LSR:   {                           DIR: '04',   IDX: '64',   EXT: '74',                 },
    MUL:   { INH: '3D',                                                                     },
    NEGA:  { INH: '40',                                                                     },
    NEGB:  { INH: '50',                                                                     },
    NEG:   {                           DIR: '00',   IDX: '60',   EXT: '70',                 },
    NOP:   { INH: '12',                                                                     },
    ORA:   {              IMM: '8A',   DIR: '9A',   IDX: 'AA',   EXT: 'BA',                 },
    ORB:   {              IMM: 'CA',   DIR: 'DA',   IDX: 'EA',   EXT: 'FA',                 },
    ORCC:  {              IMM: '1A',                                                        },
    PSHS:  {              IMM: '34',                                                        },
    PSHU:  {              IMM: '36',                                                        },
    PULS:  {              IMM: '35',                                                        },
    PULU:  {              IMM: '37',                                                        },
    ROLA:  { INH: '49',                                                                     },
    ROLB:  { INH: '59',                                                                     },
    ROL:   {                           DIR: '09',   IDX: '69',   EXT: '79',                 },
    RORA:  { INH: '46',                                                                     },
    RORB:  { INH: '56',                                                                     },
    ROR:   {                           DIR: '06',   IDX: '66',   EXT: '76',                 },
    RTI:   { INH: '3B',                                                                     },
    RTS:   { INH: '39',                                                                     },
    SBCA:  {              IMM: '82',   DIR: '92',   IDX: 'A2',   EXT: 'B2',                 },
    SBCB:  {              IMM: 'C2',   DIR: 'D2',   IDX: 'E2',   EXT: 'F2',                 },
    SEX:   { INH: '1D',                                                                     },
    STA:   {                           DIR: '97',   IDX: 'A7',   EXT: 'B7',                 },
    STB:   {                           DIR: 'D7',   IDX: 'E7',   EXT: 'F7',                 },
    STD:   {                           DIR: 'DD',   IDX: 'ED',   EXT: 'FD',                 },
    STS:   {                           DIR: '10DF', IDX: '10EF', EXT: '10FF',               },
    STU:   {                           DIR: 'DF',   IDX: 'EF',   EXT: 'FF',                 },
    STX:   {                           DIR: '9F',   IDX: 'AF',   EXT: 'BF',                 },
    STY:   {                           DIR: '109F', IDX: '10AF', EXT: '10BF',               },
    SUBA:  {              IMM: '80',   DIR: '90',   IDX: 'A0',   EXT: 'B0',                 },
    SUBB:  {              IMM: 'C0',   DIR: 'D0',   IDX: 'E0',   EXT: 'F0',                 },
    SUBD:  {              IMM: '83',   DIR: '93',   IDX: 'A3',   EXT: 'B3',                 },
    SWI:   { INH: '3F',                                                                     },
    SWI2:  { INH: '103F',                                                                   },
    SWI3:  { INH: '113F',                                                                   },
    SYNC:  { INH: '13',                                                                     },
    TFR:   {              IMM: '1F',                                                        },
    TSTA:  { INH: '4D',                                                                     },
    TSTB:  { INH: '5D',                                                                     },
    TST:   {                           DIR: '0D',   IDX: '6D',   EXT: '7D',                 },
})


OPCODES_6309 = frozendict({
    BITMD: {              IMM: '113C'                                                       },
    CMPR:  {              IMM: '1037',                                                        },
    DECD:  { INH: '104A',                                                                     },
    DECE:  { INH: '114A',                                                                     },
    DECF:  { INH: '115A',                                                                     },
    DECW:  { INH: '105A',                                                                     },
    INCD:  { INH: '004C',                                                                     }, # !! LEADING ZEROS!
    INCE:  { INH: '014C',                                                                     },
    INCF:  { INH: '015C',                                                                     },
    INCW:  { INH: '005C',                                                                     },
    LDE:   {              IMM: '0186',   DIR: '0196',   IDX: '01A6',   EXT: '01B6',         },
    LDF:   {              IMM: '01C6',   DIR: '01D6',   IDX: '01E6',   EXT: '01F6',         },
    LDQ:   {              IMM:   'CD',   DIR:   'DC',   IDX:   'EC',   EXT:   'FC',         },
    LDW:   {              IMM:   '86',   DIR:   '96',   IDX:   'A6',   EXT:   'B6',         },
    LDMD:  {              IMM: '113D',                                                      },
    STE:   {                             DIR: '0197',   IDX: '01A7',   EXT: '01B7',         },
    STF:   {                             DIR: '01D7',   IDX: '01E7',   EXT: '01F7',         },
    STQ:   {                             DIR: '00DD',   IDX: '00ED',   EXT: '00FD',         },
    STW:   {                             DIR: '0097',   IDX: '00A7',   EXT: '00B7',         },
})

OPCODES = frozendict({**OPCODES_6809, **OPCODES_6309})

# Used to interpret the unusual addressing modes of these instructions.
# From the programmers reference by Darren Atkinson:
#
#   "Unlike most other instructions which use the
#    Direct, Indexed and Extended addressing modes, the operand value used by the JMP instruction is
#    the Effective Address itself, rather than the memory contents stored at that address (unless
#    Indirect Indexing is used)."
JUMPS = {JMP, JSR}
